apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: ${email_address}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: certmanager-acme
    solvers:
    - dns01:
        cloudflare:
          email: ${cloudflare_email_address}
          apiTokenSecretRef:
            name: ${api_secret_name}
            key: api-token
      selector:
        dnsZones:
        - 'mcswain.dev'
        - 'jacob.network'
